#!/bin/sh

##########################
#### General Settings ####
##########################

set -e
set -u
#set -x # only for DEBUG

# Make available the functions defined in /lib/lsb/init-functions
. /lib/lsb/init-functions


##########################
#### Global Variables ####
##########################

USER="$(id -un 2>/dev/null || true)"

OPENBATON_BASE=/usr
OPENBATON_EXE_FOLDER=$OPENBATON_BASE/bin

OPENBATON_AUTOSTART_DEFAULT=true
OPENBATON_AUTOSTART=${OPENBATON_AUTOSTART:-$OPENBATON_AUTOSTART_DEFAULT}


##############################
#### Execution privileges ####
##############################

checkBinary () {
    if command -v $1 >/dev/null 2>&1 ; then
        log_success_msg "Checking for '$1'"
        return 0
    else
        log_failure_msg "Checking for '$1'"
        return 1
    fi
}

_ex='sh -c'
if [ "${USER}" != "root" ]; then
    if checkBinary sudo; then
        _ex='sudo -E sh -c'
    elif checkBinary su; then
        _ex='su -c'
    fi
fi


#################################################
#### Configure Open Baton GVNFM installation ####
#################################################

configure() {
    log_success_msg "Configuring Open Baton GVNFM installation .."
    log_success_msg "Giving openbaton-gvnfm execution permissions .."
    $_ex "chmod a+x ${OPENBATON_EXE_FOLDER}/openbaton-gvnfm"

    log_success_msg "Open Baton Generic VNFM installation completed"

    # Allow the use of the .deb package to install Open Baton with Docker (the Docker file developer need to manage the starting of the GVNFM in the Docker file)
    if [ "${OPENBATON_AUTOSTART}" = "true" ]; then
    	if $_ex 'systemctl start openbaton-gvnfm.service' >/dev/null 2>&1 ; then
    	    log_success_msg "Starting the Open Baton Generic VNFM .."
            continue
        elif $_ex 'start openbaton-gvnfm' >/dev/null 2>&1 ; then
    	    log_success_msg "Starting the Open Baton Generic VNFM .."
            continue
        else
            log_failure_msg "Starting the Open Baton GVNFM"
        fi
    fi
}

configure

