#!/bin/sh -e

. /lib/lsb/init-functions

OPENBATON_BASE=/usr
OPENBATON_LOGS_FOLDER=/var/log/openbaton


USER="$(id -un 2>/dev/null || true)"

checkBinary () {
    echo -n " * Checking for '$1'..."
    if command -v $1 >/dev/null 2>&1; then
        echo "OK"
        return 0
    else
        echo >&2 "FAILED."
        return 1
    fi
}

_ex='sh -c'
if [ "${USER}" != 'root' ]; then
    if checkBinary sudo; then
        _ex='sudo -E sh -c'
    elif checkBinary su; then
        _ex='su -c'
    fi
fi


#############
# OpenBaton #
#############

stopGVNFM () {
    instance=$(ps aux | grep -v grep | grep "generic-vnfm-*jar | wc -l)
    if [ ${instance} -ne 0 ]; then
    	log_daemon_msg "Stopping the OpenBaton GVNFM .."
    	$_ex 'stop openbaton-gvnfm'
    fi
}


############################################
#### Clean OpenBaton GVNFM installation ####
############################################

clean () {
    stopGVNFM
}

clean


