#!/bin/sh -e

. /lib/lsb/init-functions

OPENBATON_GVNFM_CONGIG_FILE=/etc/openbaton/gvnfm/openbaton-gvnfm.properties
INSTALL_DIR=/usr/lib/openbaton/gvnfm
PID_FILE=/var/run/openbaton-gvnfm.pid
DAEMON_USER=root
OSTYPE=$(uname)


###################
#### Rabbitmq #####
###################

check_rabbitmq () {
    if [ "${OSTYPE}" = "Linux" ]; then
        instance=$(ps aux | grep -v grep | grep rabbitmq | grep server | wc -l)
        if [ ${instance} -eq 0 ]; then
          	log_warning_msg "rabbit is not running, let's try to start it"
            start_rabbitmq
        fi
    elif [ "$OSTYPE" = "Darwin" ]; then
        instance=$(ps aux | grep -v grep | grep rabbitmq | grep server | wc -l)
        if [ ${instance} -eq 0 ]; then
            log_warning_msg "rabbitmq is not running, let's try to start it"
            start_rabbitmq
        fi
    fi
}

start_rabbitmq () {
    $(rabbitmq-server -detached)
    if [ $? -ne 0 ]; then
        log_failure_msg "rabbitmq is not running properly (check the problem in /var/log/rabbitmq.log) "
        exit 1
    fi
}


####################
#### Open Baton ####
####################

check_already_running () {
    instance=$(ps aux | grep -v grep | grep "generic-vnfm" | grep jar | wc -l)
    if [ ${instance} -ne 0 ]; then
        log_warning_msg "The Open Baton Generic VNFM is already running"
		exit 1
    fi
}

set_jar_version () {
    # TODO: so far the most recent openbaton-nfvo jar is chosen to be executed
	#       -> add alternative version selection (with prompt question and/or with command line -v parameter)
	OPENBATON_GVNFM_JAR=$(ls -ct ${INSTALL_DIR} | grep "generic-vnfm" | head -n 1)
	if [ ${OPENBATON_GVNFM_JAR} = "" ]; then
        log_failure_msg "The Open Baton Generic VNFM is not installed (jar-file not found)"
		exit 1	
    fi
}

configure () {
    check_already_running
    check_rabbitmq
    set_jar_version
}

start () {
    configure
    log_success_msg "Starting the Open Baton Generic VNFM .."

    start-stop-daemon --start --background --pidfile ${PID_FILE} --make-pidfile --user ${DAEMON_USER} --chuid ${DAEMON_USER} --exec /usr/bin/java -- -jar ${INSTALL_DIR}/${OPENBATON_GVNFM_JAR}
}

stop () {
    start-stop-daemon --stop --pidfile $PID_FILE
}

restart () {
    stop
    start
}


usage () {
    echo "Open Baton Generic VNFM"
    echo "Usage:\n\t [openbaton-gvnfm start|stop|restart] | [service openbaton-gvnfm start|stop|restart] | [start|stop openbaton-gvnfm] | [systemctl start|stop openbaton-gvnfm.service]"
}

##
#   MAIN
##

if [ ${#} -eq 0 ]
   then
        usage
        exit 1
fi

for cmd in ${@}
do
    case ${cmd} in
        "start" )
            start ;;
        "stop" )
            stop ;;
        "restart" )
            restart ;;
         *)   
	        usage;;
    esac
    if [ $? -ne 0 ];
    then
	    exit 1
    fi
done
